const Courses = [
    {
       id : "1",
       title:"web development",
       description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita incidunt tempora illum eveniet hic! Provident atque dolore ratione aliquid cupiditate quia minus, sequi aliquam eveniet, non nulla, dignissimos earum voluptas.",
       course1:"HTML",
       course2:"CSS",
       coursee:"Javascript",
       price:5000,
       image:require("../assets/image.jpg"),
    },
    {
      id : "2",
      title:"App development",
      description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita incidunt tempora illum eveniet hic! Provident atque dolore ratione aliquid cupiditate quia minus, sequi aliquam eveniet, non nulla, dignissimos earum voluptas.",
      course1:"Java",
      course2:"xml",
      coursee:"React-native",
      price:5000,
      image:require("../assets/image.jpg"),
   },
   {
    id : "3",
    title:"Graphic design",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita incidunt tempora illum eveniet hic! Provident atque dolore ratione aliquid cupiditate quia minus, sequi aliquam eveniet, non nulla, dignissimos earum voluptas.",
    course1:"HTML",
    course2:"CSS",
    coursee:"Javascript",
    price:5000,
    image:require("../assets/image.jpg"),
  },
  {
    id : "4",
    title:"web development",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita incidunt tempora illum eveniet hic! Provident atque dolore ratione aliquid cupiditate quia minus, sequi aliquam eveniet, non nulla, dignissimos earum voluptas.",
    course1:"HTML",
    course2:"CSS",
    coursee:"Javascript",
    price:5000,
    image:require("../assets/image.jpg"),
  },
  {
    id : "5",
    title:"web development",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita incidunt tempora illum eveniet hic! Provident atque dolore ratione aliquid cupiditate quia minus, sequi aliquam eveniet, non nulla, dignissimos earum voluptas.",
    course1:"HTML",
    course2:"CSS",
    coursee:"Javascript",
    price:5000,
    image:require("../assets/image.jpg"),
  },
  {
    id : "6",
    title:"web development",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita incidunt tempora illum eveniet hic! Provident atque dolore ratione aliquid cupiditate quia minus, sequi aliquam eveniet, non nulla, dignissimos earum voluptas.",
    course1:"HTML",
    course2:"CSS",
    coursee:"Javascript",
    price:5000,
    image:require("../assets/image.jpg"),
  },
  {
    id : "7",
    title:"web development",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita incidunt tempora illum eveniet hic! Provident atque dolore ratione aliquid cupiditate quia minus, sequi aliquam eveniet, non nulla, dignissimos earum voluptas.",
    course1:"HTML",
    course2:"CSS",
    coursee:"Javascript",
    price:5000,
    image:require("../assets/image.jpg"),
  },
]

export default Courses; 
